# Generated by Django 5.1.2 on 2024-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_purchase_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
