# Generated by Django 5.1.2 on 2024-12-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_rename_stock_purchaseitem_quantity_purchaseitem_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='rate',
            new_name='cost',
        ),
    ]
