# Generated by Django 5.1.2 on 2024-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0014_remove_employee_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
