# Generated by Django 5.1.2 on 2024-12-13 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_employee_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='CompanyMember',
        ),
    ]
