# Generated by Django 5.1.2 on 2024-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0019_rename_address_companie_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
