# Generated by Django 5.1.2 on 2024-12-14 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0020_product_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
