# Generated by Django 5.1.2 on 2024-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0021_product_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
