# Generated by Django 5.1.2 on 2024-12-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0022_companymember_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_total', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.companie')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_item_price', models.FloatField(blank=True, null=True)),
                ('s_item_quantity', models.IntegerField(blank=True, null=True)),
                ('s_item_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.product')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_app.sale')),
            ],
        ),
    ]
