# Generated by Django 5.1.2 on 2024-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0024_customer_alter_sale_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='company_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
